import type { Command } from 'commander'
import { writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'

const DOCS_DIR = join(import.meta.dirname, '..', 'docs')
const COMMANDS_DIR = join(DOCS_DIR, 'commands')

interface CommandInfo {
  name: string
  fullName: string
  description: string
  arguments: ArgumentInfo[]
  options: OptionInfo[]
  subcommands: CommandInfo[]
}

interface ArgumentInfo {
  name: string
  description: string
  required: boolean
}

interface OptionInfo {
  flags: string
  description: string
  defaultValue: string | undefined
}

function sanitizeDefault(value: string): string | undefined {
  if (value.includes('/') && (value.includes('home') || value.includes('Users'))) return undefined
  return value
}

function extractCommandInfo(cmd: Command, parentName = ''): CommandInfo {
  const name = cmd.name()
  const fullName = parentName ? `${parentName} ${name}` : name

  const args: ArgumentInfo[] = (cmd as unknown as { registeredArguments: Array<{ name: () => string; description: string; required: boolean }> }).registeredArguments.map(
    (arg) => ({
      name: arg.name(),
      description: arg.description,
      required: arg.required,
    }),
  )

  const options: OptionInfo[] = cmd.options
    .filter((opt) => opt.long !== '--version' && opt.long !== '--help')
    .map((opt) => ({
      flags: opt.flags,
      description: opt.description,
      defaultValue: opt.defaultValue != null ? sanitizeDefault(String(opt.defaultValue)) : undefined,
    }))

  const subcommands: CommandInfo[] = cmd.commands.map((sub) =>
    extractCommandInfo(sub as Command, fullName),
  )

  return {
    name,
    fullName,
    description: cmd.description(),
    arguments: args,
    options,
    subcommands,
  }
}

function renderCommand(cmd: CommandInfo, depth: number): string {
  const lines: string[] = []
  const heading = '#'.repeat(Math.min(depth + 2, 6))

  lines.push(`${heading} ${cmd.name}`)
  lines.push('')

  if (cmd.description) {
    lines.push(cmd.description)
    lines.push('')
  }

  const displayName = cmd.fullName.replace(/^flouz /, '')
  const usageParts = [`flouz ${displayName}`]
  for (const arg of cmd.arguments) {
    usageParts.push(arg.required ? `<${arg.name}>` : `[${arg.name}]`)
  }
  if (cmd.options.length > 0) {
    usageParts.push('[options]')
  }

  lines.push('```bash')
  lines.push(usageParts.join(' '))
  lines.push('```')
  lines.push('')

  if (cmd.arguments.length > 0) {
    lines.push('**Arguments:**')
    lines.push('')
    lines.push('| Argument | Required | Description |')
    lines.push('| --- | --- | --- |')
    for (const arg of cmd.arguments) {
      lines.push(
        `| \`${arg.name}\` | ${arg.required ? 'Yes' : 'No'} | ${arg.description || '—'} |`,
      )
    }
    lines.push('')
  }

  if (cmd.options.length > 0) {
    lines.push('**Options:**')
    lines.push('')
    lines.push('| Flag | Description | Default |')
    lines.push('| --- | --- | --- |')
    for (const opt of cmd.options) {
      lines.push(
        `| \`${opt.flags}\` | ${opt.description || '—'} | ${opt.defaultValue ? `\`${opt.defaultValue}\`` : '—'} |`,
      )
    }
    lines.push('')
  }

  for (const sub of cmd.subcommands) {
    lines.push(renderCommand(sub, depth + 1))
  }

  return lines.join('\n')
}

function generateCommandGroupPage(cmd: CommandInfo): string {
  const lines: string[] = []

  lines.push('---')
  lines.push('# This file is auto-generated by scripts/generate-command-docs.ts')
  lines.push('# Do not edit manually — changes will be overwritten.')
  lines.push('---')
  lines.push('')
  lines.push(`# ${cmd.name}`)
  lines.push('')

  if (cmd.description) {
    lines.push(cmd.description)
    lines.push('')
  }

  for (const sub of cmd.subcommands) {
    lines.push(renderCommand(sub, 0))
  }

  return lines.join('\n')
}

async function buildProgram(): Promise<Command> {
  const { createTransactionsCommand } = await import('../src/commands/transactions')
  const { createAccountsCommand } = await import('../src/commands/accounts')
  const { createBudgetCommand } = await import('../src/commands/budget')
  const { createConfigCommand } = await import('../src/commands/config')
  const { Command } = await import('commander')

  const program = new Command()
  program
    .name('flouz')
    .description('AI-powered personal finance CLI for bank transactions')
    .option('--no-color', 'Disable colored output')

  program.addCommand(await createTransactionsCommand())
  program.addCommand(await createAccountsCommand())
  program.addCommand(await createBudgetCommand())
  program.addCommand(createConfigCommand())

  return program
}

async function main(): Promise<void> {
  const program = await buildProgram()
  const root = extractCommandInfo(program)

  mkdirSync(COMMANDS_DIR, { recursive: true })

  for (const group of root.subcommands) {
    const content = generateCommandGroupPage(group)
    const filePath = join(COMMANDS_DIR, `${group.name}.md`)
    writeFileSync(filePath, content)
    console.log(`Generated: docs/commands/${group.name}.md`)
  }

  console.log(`\nDone — ${root.subcommands.length} command pages generated.`)
}

main().catch((err) => {
  console.error('Failed to generate command docs:', err)
  process.exit(1)
})
